before_script:
  - curl -k -L -o browsermob-proxy.zip https://s3-us-west-1.amazonaws.com/lightbody-bmp/browsermob-proxy-2.0-beta-8-bin.zip
  - unzip browsermob-proxy.zip
  - export BMP_PATH=$TRAVIS_BUILD_DIR/browsermob-proxy-2.0-beta-8

language: python
python:
  - 2.6
  - 2.7

install: python setup.py install

script: py.test testing

notifications:
  email:
    - dave.hunt@gmail.com
  irc:
    - "irc.mozilla.org#automation"
    - "irc.mozilla.org#mozwebqa"
