before_script:
  - curl -k -L -o /tmp/browsermob-proxy.zip https://s3-us-west-1.amazonaws.com/lightbody-bmp/browsermob-proxy-2.0-beta-8-bin.zip
  - sudo unzip /tmp/browsermob-proxy.zip -d /tmp
  - ln -s /tmp/browsermob-proxy-2.0-beta-8 /tmp/browsermob-proxy

language: python
python:
  - 2.6
  - 2.7

install: python setup.py install

script: py.test testing

notifications:
  email:
    - dave.hunt@gmail.com
  irc:
    - "irc.mozilla.org#automation"
    - "irc.mozilla.org#mozwebqa"
